// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-trending-songs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/pocketbase.ts
function pocketBaseUrl() {
  const deno = globalThis.Deno;
  const runtimeEnv = deno ? { POCKETBASE_URL: deno.env.get("POCKETBASE_URL"), VITE_PB_URL: deno.env.get("VITE_PB_URL") } : { POCKETBASE_URL: process.env.POCKETBASE_URL, VITE_PB_URL: process.env.VITE_PB_URL };
  const url = runtimeEnv.POCKETBASE_URL?.trim() || runtimeEnv.VITE_PB_URL?.trim();
  if (!url) {
    throw new Error("POCKETBASE_URL is not configured for the MCP server.");
  }
  const parsed = new URL(url);
  if (parsed.protocol !== "https:" && parsed.protocol !== "http:") {
    throw new Error("POCKETBASE_URL must be an http(s) URL.");
  }
  return parsed.toString().replace(/\/$/, "");
}
function escapePocketBaseFilter(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
async function listPocketBaseRecords(collection, options = {}) {
  const page = options.page ?? 1;
  const perPage = options.perPage ?? 20;
  const url = new URL(`${pocketBaseUrl()}/api/collections/${encodeURIComponent(collection)}/records`);
  url.searchParams.set("page", String(page));
  url.searchParams.set("perPage", String(perPage));
  if (options.filter) url.searchParams.set("filter", options.filter);
  if (options.sort) url.searchParams.set("sort", options.sort);
  const response = await fetch(url, {
    headers: { Accept: "application/json" },
    redirect: "error"
  });
  if (!response.ok) {
    throw new Error(`PocketBase request failed (${response.status}).`);
  }
  const data = await response.json();
  return Array.isArray(data.items) ? data.items : [];
}
function publicFileUrl(record, filename) {
  if (typeof filename !== "string" || !filename) return null;
  const collection = record.collectionId || record.collectionName;
  if (!collection) return null;
  return `${pocketBaseUrl()}/api/files/${encodeURIComponent(collection)}/${encodeURIComponent(record.id)}/${encodeURIComponent(filename)}`;
}
function publicSong(record) {
  const coverUrl = typeof record.cover_url === "string" && record.cover_url ? record.cover_url : publicFileUrl(record, record.cover);
  return {
    id: record.id,
    title: typeof record.title === "string" ? record.title : "",
    author: typeof record.author === "string" ? record.author : "",
    genre: typeof record.genre === "string" && record.genre ? record.genre : null,
    durationSeconds: typeof record.duration === "number" ? record.duration : 0,
    playCount: typeof record.play_count === "number" ? record.play_count : 0,
    weeklyPlayCount: typeof record.weekly_play_count === "number" ? record.weekly_play_count : 0,
    likesCount: typeof record.likes_count === "number" ? record.likes_count : 0,
    coverUrl
  };
}

// src/lib/mcp/tools/list-trending-songs.ts
var list_trending_songs_default = defineTool({
  name: "list_trending_songs",
  title: "Titres tendance",
  description: "Liste les morceaux publics les plus \xE9cout\xE9s sur Jux Music pendant la p\xE9riode hebdomadaire en cours.",
  inputSchema: {
    limit: z.number().int().optional().describe("Nombre maximal de titres, de 1 \xE0 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const safeLimit = Math.min(Math.max(limit ?? 10, 1), 10);
    try {
      const records = await listPocketBaseRecords("songs", {
        perPage: safeLimit,
        sort: "-weekly_play_count,-play_count"
      });
      const songs = records.map((record, index) => ({ rank: index + 1, ...publicSong(record) }));
      return {
        content: [{ type: "text", text: songs.length ? JSON.stringify(songs) : "Aucun titre tendance disponible." }],
        structuredContent: { songs }
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: error instanceof Error ? error.message : "Tendances indisponibles." }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/search-songs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_songs_default = defineTool2({
  name: "search_songs",
  title: "Rechercher des titres",
  description: "Recherche des morceaux publics du catalogue Jux Music par titre, artiste ou genre.",
  inputSchema: {
    query: z2.string().trim().describe("Titre, artiste ou genre \xE0 rechercher."),
    limit: z2.number().int().optional().describe("Nombre maximal de r\xE9sultats, de 1 \xE0 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const safeLimit = Math.min(Math.max(limit ?? 10, 1), 20);
    const term = escapePocketBaseFilter(query.slice(0, 100));
    const filter = term ? `title ~ "${term}" || author ~ "${term}" || genre ~ "${term}"` : void 0;
    try {
      const records = await listPocketBaseRecords("songs", {
        perPage: safeLimit,
        filter,
        sort: "-weekly_play_count,-play_count"
      });
      const songs = records.map(publicSong);
      return {
        content: [{ type: "text", text: songs.length ? JSON.stringify(songs) : "Aucun titre trouv\xE9." }],
        structuredContent: { songs }
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: error instanceof Error ? error.message : "Recherche indisponible." }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jux-music-mcp",
  title: "Jux Music",
  version: "0.1.0",
  instructions: "Outils publics et en lecture seule pour d\xE9couvrir le catalogue musical Jux Music et ses tendances. N'utilise jamais ces outils pour modifier des donn\xE9es.",
  tools: [search_songs_default, list_trending_songs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
